#!/bin/bash

trap 'exit' INT

RPI_USER="pi"
RPI_ADDR="192.168.2.2"

if [ "$1" == "-h" ] || [ "$1" == "--help" ]
then
  echo "usage: raspi-prepare [RPI_USER RPI_ADDR]"
  echo "	default RPI_USER=pi"
  echo "	default RPI_ADDR=192.168.2.2"
  exit 0
fi

if [ ! "$1" == "" ]
then
  RPI_USER=$1
fi

if [ ! "$2" == "" ]
then
  RPI_ADDR=$2
fi

TIMESTAMP=`ruby -e 'puts (Time.now.to_f * 1000000).to_i'`

echo "Info:	RPI_USER=$RPI_USER"
echo "Info:	RPI_ADDR=$RPI_ADDR"
echo "Info:	TIMESTAMP=$TIMESTAMP"

if [ -e $HOME/.ssh/config ]
then
  echo "Info:	Create $HOME/.ssh/config.backup"
  cp $HOME/.ssh/config $HOME/.ssh/config.backup

  echo "Info:	Apply changes to the backup"
  sed  -i ".buffer" "s/rpi\.[0-9]*$/rpi.$TIMESTAMP/"  $HOME/.ssh/config.backup
else
  echo "Info:	Add the following settings into $HOME/.ssh/config"
  cat <<EOF | tee -a $HOME/.ssh/config.backup
Host rpi
    HostName        $RPI_ADDR
    IdentityFile    $HOME/.ssh/id_ecdsa.rpi.$TIMESTAMP
    User            $RPI_USER
EOF
fi

echo "Info:	Create new key pair"
ssh-keygen -t ecdsa -b 521 -f "$HOME/.ssh/id_ecdsa.rpi.$TIMESTAMP"

if [ -e $HOME/.ssh/config ] || [ "$1" == "-f" ]
then
  RPI_HOST=rpi
else
  RPI_HOST="$RPI_USER@$RPI_ADDR"
fi

echo "Info:	Create /home/$RPI_USER/.ssh if not exists"
echo '[ -d $HOME/.ssh ] || mkdir $HOME/.ssh' | ssh $RPI_HOST sh

echo "Info:	Add the pub key to /home/$RPI_USER/.ssh/authorized_keys"
cat $HOME/.ssh/id_ecdsa.rpi.$TIMESTAMP.pub | ssh $RPI_HOST tee -a '$HOME/.ssh/authorized_keys'

echo "Info:	Expand root file system"
cat ./expand_rootfs.sh | ssh $RPI_HOST sudo sh

echo "Info:	Apply changes from the backup"
cp $HOME/.ssh/config.backup $HOME/.ssh/config

echo "🍺  Successfully done!"
