#!/bin/bash

RPI_USER="pi"
RPI_ADDR="192.168.2.2"
TIME_STAMP=`ruby -e 'puts (Time.now.to_f * 1000000).to_i'`

if [ -e $HOME/.ssh/config ]
then
  echo "Info:	Copy backup"
  cp $HOME/.ssh/config $HOME/.ssh/config.backup
  echo "Info:	Rename old settings"
  sed  -i buffer_string "s/rpi\.[0-9]*$/rpi.$TIME_STAMP/"  $HOME/.ssh/config.backup
else
  echo "Info:	Add the following settings into $HOME/.ssh/config"
  cat <<EOF | tee -a $HOME/.ssh/config.backup
Host rpi
    HostName        $RPI_ADDR
    IdentityFile    $HOME/.ssh/id_ecdsa.rpi.$TIME_STAMP
    User            $RPI_USER
EOF
fi

echo "Info:	Creating new key pair"
ssh-keygen -t ecdsa -b 521 -f "$HOME/.ssh/id_ecdsa.rpi.$TIME_STAMP"

echo "Info:	On RPI, Create \$HOME/.ssh dir if not exists"
echo '[ -d $HOME/.ssh ] || mkdir $HOME/.ssh' | ssh rpi sh

echo "Info:	Add pub key into RPI"
cat $HOME/.ssh/id_ecdsa.rpi.$TIME_STAMP.pub | ssh rpi tee -a '$HOME/.ssh/authorized_keys'

echo "Info:	Expand root file system"
cat ./expand_rootfs.sh | ssh rpi sudo sh

echo "Info:	Apply changes"
cp $HOME/.ssh/config.backup $HOME/.ssh/config

echo "🍺  Successfully done!"
